version: 0.0
os: linux
files:
  - source: initial/target/gs-spring-boot-0.1.0.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/applicationstop.sh
      timeout: 60
      runas: root   
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root     