version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ls -l
  post_build:
    commands:
      - echo Build completed on `date`
      - cd initial && mvn clean package
      - ls -l
artifacts:
  files:
    - initial/target/gs-spring-boot-0.1.0.jar
    - appspec.yml
    - scripts/*
  discard-paths: no
